### ISSUE TITLE
how to contact you 

### ISSUE THREAD

**Issue by ri-sh** [JackZProduction/python_chat#2]
the following errors occur and the client unable to connect to the host 

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python27\Lib\lib-tk\Tkinter.py", line 1410, in **call**
    return self.func(_args)
  File "C:\Users\kiit\Desktop\python_chat-master\client.pyw", line 37, in PressAction
    ClickAction()
  File "C:\Users\kiit\Desktop\python_chat-master\client.pyw", line 30, in ClickAction
    s.sendall(EntryText)
  File "C:\Python27\Lib\socket.py", line 224, in meth
    return getattr(self._sock,name)(_args)
error: [Errno 10057] A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied

**Comment by Drmicrosoft** [comment]
how to run the code on linux ?
